apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress-service
  namespace: ingress
  annotations:
    kubernetes.io/ingress.class: nginx  
spec:
  rules:
    - http:
        paths:
          - path: /employee
            pathType: Prefix
            backend:
              service:
                name: service-employee-producer-pod
                port: 
                  number: 8000        
          - path: /empcertifications
            pathType: Prefix
            backend:
              service:
                name: service-cert-pod 
                port: 
                  number: 9000

