apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod-secret
  labels: 
    app: frontend-label
    type: frontend
spec:
  containers:
    - name: frontend-pod
      image: aksbyexampleacr.azurecr.us/employee-cert:1.0-amd64
      ports:
        - containerPort: 9000
      envFrom:
        - secretRef:
            name: oracle-database-secret
