apiVersion: v1
kind: Pod
metadata:
  name: payment-processing-pod-env
  labels: 
    app: payment-processing-label
    type: payment-processing
spec:
  containers:
    - name: payment-processing-pod
      image: aksbyexampleacr.azurecr.us/employee-cert:1.0-amd64
      ports:
        - containerPort: 9000
      env: 
        - name: PAYPAL_URL
          value: https://paypal-gateway.com
        - name: PAYPAL_CLIENT_ID
          value: AMZN
        - name: PAYPAL_SECURE_TOKEN
          value: a419789e-40e4
        